# The below URL is hardcoded since Mhathesh has deployed this to BND.
# Also see: https://github.com/pacenthink/pacenthink.io/pull/10#discussion_r1095238635
baseURL = ''
languageCode = 'en-us'
title = "Pace 'n Think"
theme = 'hugo-PaperMod'

[Params]
  ShowBreadCrumbs = 'true'
  ShowShareButtons = 'true'
  ShowReadingTime = "true"
  ShowPostNavLinks = 'true'
  ShowRssButtonInSectionTermList = 'true'
  UseHugoToc = 'true'
