baseURL = 'http://www.pacenthink.io/'
languageCode = 'en-us'
title = "Pace 'n Think"
theme = 'hugo-PaperMod'

[Params]
  ShowBreadCrumbs = 'true'
  ShowShareButtons = 'true'
  ShowReadingTime = "true"
  ShowPostNavLinks = 'true'
  ShowRssButtonInSectionTermList = 'true'
  UseHugoToc = 'true'

[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

