baseURL = 'http://www.pacenthink.io/'
languageCode = 'en-us'
title = "Pace 'n Think"
theme = 'hugo-PaperMod'

[Params]
  ShowBreadCrumbs = 'true'
  ShowShareButtons = 'true'
  ShowReadingTime = "true"
  ShowPostNavLinks = 'true'
  ShowRssButtonInSectionTermList = 'true'
  UseHugoToc = 'true'

