# The below URL is hardcoded since Mhathesh has deployed this to BND.
baseURL = 'https://pacenthinkio-maddy023-devops.pacenthink.co/'
languageCode = 'en-us'
title = "Pace 'n Think"
theme = 'hugo-PaperMod'

[Params]
  ShowBreadCrumbs = 'true'
  ShowShareButtons = 'true'
  ShowReadingTime = "true"
  ShowPostNavLinks = 'true'
  ShowRssButtonInSectionTermList = 'true'
  UseHugoToc = 'true'