baseURL = 'https://comforting-quokka-174fd1.netlify.app/'
languageCode = 'en-us'
title = "Pace 'n Think"
theme = 'PaperMod'

[Params]
  ShowBreadCrumbs = 'true'
  ShowShareButtons = 'true'
  ShowReadingTime = 'true'
  ShowPostNavLinks = 'true'
  ShowWordCount = 'true'
  ShowRssButtonInSectionTermList = 'true'
  UseHugoToc = 'true'
  disableSpecial1stPost = 'true'
  disableScrollToTop = 'true'
  comments = 'true'
  hidemeta = 'true'
  hideSummary = 'true'
  showtoc = 'true'
  tocopen = 'true'
  author = 'Me'

[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

